apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sentry-tls
  namespace: sentry
spec:
  secretName: sentry-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - sentry.domain.com
